Repository Guikingone/SchedulerBundle, pull requests merged in 2021-01, with the labels that each got.

#4 Readme: docs tree & wording
  README.md
Labels: documentation

#1 feat(task) NotificationBag
  LICENSE
  composer.json
  doc/tasks.md
  phpstan.neon.dist
  src/DependencyInjection/SchedulerBundleExtension.php
  src/Scheduler.php
  src/Task/AbstractTask.php
  src/Task/TaskInterface.php
  src/Task/TaskList.php
  src/TaskBag/NotificationTaskBag.php
  src/TaskBag/TaskBagInterface.php
  src/Transport/AbstractTransport.php
  src/Worker/Worker.php
  tests/DependencyInjection/SchedulerBundleExtensionTest.php
  tests/SchedulerTest.php
  tests/Serializer/TaskNormalizerTest.php
  tests/Task/NullTaskTest.php
  tests/TaskBag/NotificationTaskBagTest.php
  tests/Worker/WorkerTest.php
Labels: documentation, enhancement

#5 feat(core): lifecycle subscribers
  .github/workflows/daily.yml
  .github/workflows/push.yml
  composer.json
  psalm.xml
  src/Bridge/Doctrine/Transport/Connection.php
  src/Bridge/Redis/Transport/RedisTransport.php
  src/DependencyInjection/SchedulerBundleExtension.php
  src/EventListener/TaskLifecycleSubscriber.php
  src/EventListener/WorkerLifecycleSubscriber.php
  src/Scheduler.php
  src/Transport/FilesystemTransport.php
  src/Transport/InMemoryTransport.php
  tests/DependencyInjection/SchedulerBundleExtensionTest.php
  tests/EventListener/TaskLifecycleSubscriberTest.php
  tests/EventListener/WorkerLifecycleSubscriberTest.php
Labels: enhancement
