Repository Guikingone/SchedulerBundle, pull requests merged in 2021-02, with the labels that each got.

#2 doc(transports): Improvements
  README.md
  doc/runners.md
  doc/transport.md
  doc/worker.md
Labels: documentation

#6 build(deps): Sf package update
  .github/workflows/daily.yml
  .github/workflows/push.yml
  CHANGELOG.md
  composer.json
  src/Bridge/Doctrine/SchemaListener/SchedulerTransportDoctrineSchemaSubscriber.php
  src/Bridge/Doctrine/Transport/Connection.php
  src/Bridge/Redis/Transport/Connection.php
  src/Command/RebootSchedulerCommand.php
  src/DependencyInjection/SchedulerBundleExtension.php
  src/EventListener/TaskSubscriber.php
  src/Runner/CallbackTaskRunner.php
  src/Runner/MessengerTaskRunner.php
  src/Runner/NotificationTaskRunner.php
  src/Runner/ShellTaskRunner.php
  src/Serializer/NotificationTaskBagNormalizer.php
  src/Serializer/TaskNormalizer.php
  src/Task/AbstractTask.php
  src/Task/CallbackTask.php
  src/Task/Output.php
  src/Task/ShellTask.php
  src/Task/TaskInterface.php
  src/Task/TaskList.php
  src/Task/TaskListInterface.php
  src/Transport/AbstractTransport.php
  src/Transport/ConnectionInterface.php
  src/Transport/Dsn.php
  src/Transport/FailoverTransport.php
  src/Transport/FilesystemTransport.php
  src/Transport/FilesystemTransportFactory.php
  src/Transport/InMemoryTransport.php
  src/Transport/RoundRobinTransport.php
  src/Transport/TransportInterface.php
  src/Worker/Worker.php
  src/Worker/WorkerInterface.php
  tests/Bridge/Doctrine/SchemaListener/SchedulerTransportDoctrineSchemaSubscriberTest.php
  tests/Bridge/Doctrine/Transport/ConnectionIntegrationTest.php
  tests/Bridge/Redis/Transport/ConnectionIntegrationTest.php
  tests/DependencyInjection/SchedulerBundleExtensionTest.php
  tests/EventListener/StopWorkerOnFailureLimitSubscriberTest.php
  tests/EventListener/TaskSubscriberTest.php
  tests/Runner/CallBackTaskRunnerTest.php
  tests/Runner/NotificationTaskRunnerTest.php
  tests/Runner/ShellTaskRunnerTest.php
  tests/Serializer/NotificationTaskBagNormalizerTest.php
  tests/Serializer/TaskNormalizerTest.php
  tests/Task/CallbackTaskTest.php
  tests/Task/CommandTaskTest.php
  tests/Task/NullTaskTest.php
  tests/Test/Constraint/TaskQueuedTest.php
  tests/Transport/FailoverTransportTest.php
  tests/Transport/FilesystemTransportFactoryTest.php
  tests/Transport/FilesystemTransportTest.php
  tests/Transport/InMemoryTransportTest.php
Labels: bug, enhancement

#8 refactor(serializer): improvements
  Makefile
  src/Serializer/NotificationTaskBagNormalizer.php
  src/Serializer/TaskNormalizer.php
  tests/Serializer/NotificationTaskBagNormalizerTest.php
Labels: enhancement

#10 ci(push): pull_request support added
  .github/workflows/push.yml
Labels: CI

#11 ci(cache): PHPUnit result cache added
  .github/workflows/push.yml
Labels: CI, Improvement

#17 build(doctrine): core dependencies updated
  .github/workflows/daily.yml
  .github/workflows/push.yml
  CHANGELOG.md
  composer.json
  phpstan.neon.dist
  src/Bridge/Doctrine/Transport/Connection.php
  src/Bridge/Doctrine/Transport/DoctrineTransport.php
  src/Bridge/Doctrine/Transport/DoctrineTransportFactory.php
  src/SchedulePolicy/DeadlinePolicy.php
  src/Test/Constraint/TaskQueued.php
  src/Transport/Dsn.php
  tests/Bridge/Doctrine/SchemaListener/SchedulerTransportDoctrineSchemaSubscriberTest.php
  tests/Bridge/Doctrine/Transport/ConnectionTest.php
  tests/Bridge/Doctrine/Transport/DoctrineTransportFactoryTest.php
  tests/Bridge/Doctrine/Transport/DoctrineTransportTest.php
Labels: Improvement, PHP

#18 Split workflows
  .github/workflows/code-style.yml
  .github/workflows/infection.yml
  .github/workflows/phpunit.yml
  .github/workflows/push.yml
  .github/workflows/rector.yml
  .github/workflows/static-analysis.yml
  composer.json
Labels: CI, Improvement

#20 ci(infection): badge added
  README.md
  infection.json.dist
Labels: CI, Improvement

#26 feat(task): fluent expression WIP
  CHANGELOG.md
  README.md
  composer.json
  doc/best_practices.md
  doc/scheduler.md
  doc/tasks.md
  psalm.xml
  src/Command/ConsumeTasksCommand.php
  src/Command/ListFailedTasksCommand.php
  src/Command/ListTasksCommand.php
  src/Command/RebootSchedulerCommand.php
  src/DependencyInjection/SchedulerBundleExtension.php
  src/Expression/BuilderInterface.php
  src/Expression/ComputedExpressionBuilder.php
  src/Expression/CronExpressionBuilder.php
  src/Expression/Expression.php
  src/Expression/ExpressionBuilder.php
  src/Expression/ExpressionBuilderInterface.php
  src/Expression/FluentExpressionBuilder.php
  src/Messenger/TaskToPauseMessage.php
  src/Messenger/TaskToPauseMessageHandler.php
  src/Middleware/AbstractMiddlewareStack.php
  src/SchedulePolicy/BatchPolicy.php
  src/SchedulePolicy/DeadlinePolicy.php
  src/SchedulePolicy/FirstInFirstOutPolicy.php
  src/SchedulePolicy/FirstInLastOutPolicy.php
  src/SchedulePolicy/MemoryUsagePolicy.php
  src/SchedulePolicy/NicePolicy.php
  src/Scheduler.php
  src/SchedulerInterface.php
  src/Task/AbstractTask.php
  src/Task/Builder/AbstractTaskBuilder.php
  src/Task/Builder/BuilderInterface.php
  src/Task/Builder/ChainedBuilder.php
  src/Task/Builder/CommandBuilder.php
  src/Task/Builder/HttpBuilder.php
  src/Task/Builder/NullBuilder.php
  src/Task/Builder/ShellBuilder.php
  src/Transport/LongTailTransport.php
  src/Worker/WorkerInterface.php
  tests/Bridge/Doctrine/Transport/ConnectionTest.php
  tests/Command/ConsumeTasksCommandTest.php
  tests/DependencyInjection/SchedulerBundleExtensionTest.php
  tests/Expression/ComputedExpressionBuilderTest.php
  tests/Expression/CronExpressionBuilderTest.php
  tests/Expression/ExpressionBuilderTest.php
  tests/Expression/ExpressionTest.php
  tests/Expression/FluentExpressionBuilderTest.php
  tests/Messenger/TaskToPauseMessageHandlerTest.php
  tests/Messenger/TaskToPauseMessageTest.php
  tests/Middleware/SchedulerMiddlewareStackTest.php
  tests/SchedulerTest.php
  tests/Task/Builder/ChainedBuilderTest.php
  tests/Task/Builder/CommandBuilderTest.php
  tests/Task/Builder/HttpBuilderTest.php
  tests/Task/Builder/NullBuilderTest.php
  tests/Task/Builder/ShellBuilderTest.php
  tests/Task/TaskBuilderTest.php
  tests/Transport/LongTailTransportTest.php
Labels: PHP
